version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  ignore:
  - dependency-name: babelify
    versions:
    - ">= 0"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
