version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: babelify
    versions:
    - ">= 0"
  - dependency-name: gulp-xml-validator
    versions:
    - "> 1.0.0"
  - dependency-name: gulp-imagemin
    versions:
    - "> v7.1.0"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: dockershelf/node
    versions:
    - "> 14"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "01:00"
  open-pull-requests-limit: 99
