sudo: required
services: docker
dist: trusty
group: edge
branches:
    only:
        - staging
        - develop
        - /^greenkeeper/.*$/
env:
    global:
        # Github personal access token ${GHTOKEN}
        - secure: "HlPlRD7aMngVSbeUMps+CPhiP6ax3tUtQGS3G6V072iF8eNS8kPo6jo+q5mH5i5zU8eV4uidkSCVwC9WSrgpxg/3edmUO+u+KOErs9gagzQ5mQ44PEDtQeNOnVGi4GespQknkTHKtsogQQ0srUJcALbdpzNtgnKW1Agfs8QxJ7g="
before_script:
    - mkdir -p bower_components node_modules vendor/bundle
    - sudo chown -R 1000:1000 .
    - make image
    - make dependencies
script:
    - make build_development
    - make build_production
    - sudo chown -R ${USER}:${USER} .
    - cp CNAME build/production
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GHTOKEN
    local-dir: build/production
    target-branch: master
    committer-from-gh: true
    verbose: true
    on:
        branch: staging