version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "babelify"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"